# Generated by Django 4.0.6 on 2023-07-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John Doe', max_length=255)),
                ('telephone_number', models.CharField(default='N/A', max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('city', models.CharField(default='Default City', max_length=255)),
                ('street', models.CharField(default='Default Street', max_length=255)),
                ('apartment', models.CharField(default='N/A', max_length=50)),
                ('zipcode', models.CharField(default='00000', max_length=7)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Default', max_length=50)),
                ('payment_intent', models.CharField(default='Default', max_length=50)),
                ('tracking_number', models.CharField(default='Default', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='base.order')),
            ],
        ),
    ]
